from linked_lists import LinkedList, DoublyLinkedList

# ll = LinkedList()
# ll.print()
# ll.add_from_iter(['One','Two','Three'])
# ll.print()
# ll.add_to_beginning('Zero')
# ll.print()
# ll.add_to_end('Four')
# ll.print()
# print(ll.get_length())
# ll.add_at(1,'Another One')
# ll.print()
# ll.remove_at(1)
# ll.print()
# ll.add_after_value('One','Another One')
# ll.print()
# ll.remove_after_value('One')
# ll.print()

dll = DoublyLinkedList()
dll.print_forward()
dll.add_to_beginning('Hi')
dll.print_forward()
dll.add_to_beginning('Hello')
print(dll.print_forward())
print(dll.print_backward())
print(dll.get_length())
dll.add_at_index(1,'Welcome')
print(dll.print_backward())
print(dll.NODES)
dll.remove_at(1)
print(dll.print_backward())
# print(dll.NODES)
print(dll.print_forward())
dll.add_from_iterable([5,6,7])
print(dll.print_forward())
dll.remove_at(3)
print(dll.print_forward())
# print(dll.NODES)
dll.insert_after_value(5,20)
print(dll.NODES)
dll.remove_after_value(20)
print(dll.NODES)